### ISSUE TITLE
Test harness should gracefully handle autogenerated fields when using table-lists

### ISSUE THREAD

**Issue by kitsao** [medic/medic-conf-test-harness#19]
Appearance `table-list` results in pyxform autogenerating two input fields, `generated_table_list_label_{row number}: ''` and `reserved_name_for_field_list_labels_{row number}: ''`. These require inputs when running unit tests, which does not match the UI.

**To Reproduce**
1. Create a simple xform, add an input group (set appearance to `table-list`) with one or two inputs
2. Convert the form, notice the extra fields on the `xml`
3. Run a unit test for the same
4. See error trail, `"msg": "Attempted to fill {n} questions, but only {n-1/2/...} are visible."

**Expected behavior**
Unit test input count should match UI's, even though resulting JSON doc shall still have the extra fields. e.g.
```
"generated_table_list_label_132": "",
"reserved_name_for_field_list_labels_133": "",
```

**Additional context**
A workaround is to add inputs to the set of inputs to cater to the extra fields, and the tests pass.

**Comment by iesmail-znz** [comment]
Here's the form inputs for postpartum form: 
```
 postpartum: {
        has_other_danger_signs: [
            [], [], [], ['no', 'no', 'no','no'], Array(15).fill('yes'),
            [], [], [],[]
        ]
    }
```

This is the postpartum test: 

```
 it(`Client has other danger signs`, async () => {
    const result = await harness.fillForm(formName, ...postpartum.has_other_danger_signs);
    console.log("POSRPARTUM ERROR: " , result.errors); 
    await new Promise(resolve => {});
    expect(result.errors).to.be.empty;
    // Verify that the referral attribute has value of 1
    expect(result.report.fields).to.deep.include({
      refer_postpartum_emergency_danger_sign_flag: '1',
    });
  });
```

**Comment by kennsippell** [comment]
@iesmail-znz @kitsao Can one of you attach an `xml` form that reproduces this issue?
