### ISSUE TITLE
Infant-child form input mismatch 

### ISSUE THREAD

**Issue by iesmail-znz** [medic/medic-conf-test-harness#23]
In the D-Tree Infant child form, there is a set of questions about danger signs for a 6 month old child .  The following set of inputs are supposed to cover the flow of this test case: 

```
has_child_danger_signs: [
            [],
            ['yes'],
            [],
            Array(10).fill('yes'),
            ['green','present'],
			[],
			['no'],
			['mother','stage_9mo_to_12mo','yes','responds_sounds'],
			['moves','yes','no'],
			['no','no','mother','2','no','no','no','no'],
			['no'],['no'],[],[],['no'],[]		
        ],
```
However, there are two questions which are unanswered when the test is run, although the answers to these questions are already covered in the inputs above. 

![image (1)](https://user-images.githubusercontent.com/49481318/74027881-24e5b500-49ba-11ea-9ee9-9696d4ad9bba.png)

**Comment by kennsippell** [comment]
Fixed in medic-conf-test-harness@0.1.21

FYI these are the inputs I got working. Perhaps my content or user was slightly different than yours.

```
const inputs = [
        [],
        ['yes'],
        [],
        Array(10).fill('yes'),
        ['green','present'],
        ['no'],
        ['mother', 'stage_9mo_to_12mo', 'yes', 'does_not_talk'],
        ['moves', 'yes', 'no'],
        ['no','no','played','mother','2','no','no','no','no', '5', 'no', '1', '1', 'yes', 'no'],
        ['no'],
        ['no'],
        [],
        ['no'],
        []		
      ];
```
