### ISSUE TITLE
Form calculate field not updating

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-conf-test-harness#75]
```
const fp_screening = await harness.fillForm('fp_screening',
      [
        'no',
        'no',
        'yes',
        new Date().toISOString().slice(0, 10),
        'yes'
      ]
    );
```
The field observed not updating `refer_to_hf`, expected to be calculated to 'yes' with the responses above but still defaults to 'no'

[fp_screening form can be downloaded here](https://github.com/medic/medic-conf-test-harness/files/5677239/fp_screening.xlsx)

**Comment by kennsippell** [comment]
Taking on triage and deep understanding of this issue in Sprint 14.

**Comment by kennsippell** [comment]
@eljhkrr  The following assertion fails:

`expect(result.report.fields.refer_to_hf).to.eq('yes');`

Looking at the definition of `refer_to_hf`, it appears to be defined as `<bind calculate="if(selected(../wants_fp, 'yes') or selected(../change_fp, 'yes'), 'yes', 'no')" nodeset="/fp_screening/refer_to_hf" type="string"/>`

But the wants_fp and change_fp paths both seem incorrect. If I update to use the proper path `<bind calculate="if(selected(../fp_screening/wants_fp, 'yes') or selected(../fp_screening/change_fp, 'yes'), 'yes', 'no')" nodeset="/fp_screening/refer_to_hf" type="string"/>` then the calculation works. It seems this is a legitimate bug in the form, would you confirm?

**Comment by eljhkrr** [comment]
The form has been fixed and the calculation is updating correctly. Thank you for the feedback!
