### ISSUE TITLE
Muting forms don't mute contacts under harness

### ISSUE THREAD

**Issue by pkitutu** [medic/medic-conf-test-harness#79]
### How to reproduce
- Create muting forms
- Enable muting mode in App settings and specify the muting forms
- Create a unit test and apply a muting form to the harness contact

### Expected Result
- An attribute created on harness Contact of `muted` with value of `date_muted` once the mute form has been applied to it

**Comment by kennsippell** [comment]
This won't be possible through the integration testing framework. Writing automation for this will require an E2E test method. 
https://docs.google.com/presentation/d/1HNb7uQfmXkTg5VrTEMZgC-RylboQLey_I9BqqYmlZu0/edit#slide=id.g85808645dd_0_151
