### ISSUE TITLE
Css on documentation page not loading due to CORS

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf-test-harness#91]
Offical [README.md](https://github.com/medic/medic-conf-test-harness/blob/master/README.md) links to https://htmlpreview.github.io/?https://raw.githubusercontent.com/medic/medic-conf-test-harness/blob/master/out/index.html

This previously showed the full documentation + loaded all required CSS. Looks like the CSS is no longer loading and we need a better way to produce this documentation.

**Comment by derickl** [comment]
Can we consider github pages? I heven't done much reading but seems possible: https://codeburst.io/generate-docs-and-host-it-with-jsdoc-and-github-pages-113b9dae9acb

**Comment by kennsippell** [comment]
@derickl You want to give it a try in sprint 20?
